# Generated by Django 4.2.7 on 2025-03-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_shop_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rule',
            new_name='role',
        ),
    ]
