# Generated by Django 4.2.7 on 2025-03-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0006_remove_products_shop_shop_buyer_alter_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
